import openai

api_endpoint = "https://api.openai.com/v1/completions"
openai.api_key = "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"

model_engine = "text-davinci-003"
prompt = "Hello, how are you today?"

completion = openai.Completion.create(
    engine = model_engine,
    prompt = prompt,
    max_toxens = 100, #max length of answer generated by openai
    n = 1, #represents the amount of answers given
    stop = None,
    temperature = 0.5, #internal parameter
)

response = completion.choices[0].text
print(response)

